In [1]:
from P1 import *
from P2 import *
from P3 import *

In [3]:
load_plants()

,id,name,location,date_acquired,watering_frequency,sunlight,last_watered
0,2a9902a4-43d6-4b46-8330-de1067281f8f,Cactus,Garden,01-02-2025,7,High,20-06-2026

In [4]:
load_care_log()

Empty DataFrame
Columns: [plant_id, activity, dat]
Index: []

In [2]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 1
Press Enter to continue or 'b' to go back:
Enter Plant name/species:  Cactus
Location in home:  Garden
Date acquired "Day-Month-Year" :  01-02-2025
Watering frequency (in days) : 7
Sunlight needs (Low, Medium, High) : high
When was the plant last watered? "Day-Month-Year": 20-06-2026

Cactus has been added to the plants file with id: 2a9902a4-43d6-4b46-8330-de1067281f8f.

In [4]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 3

 Plants due for care:
-------------------------
 Cactus - last watered 11 days ago (every 7 days)
-------------------------

In [6]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 1
Press Enter to continue or 'b' to go back:
Enter Plant name/species:  Mango
Location in home:  Garden
Date acquired "Day-Month-Year" :  01-01-2026
Watering frequency (in days) : 4
Sunlight needs (Low, Medium, High) : low
When was the plant last watered? "Day-Month-Year": 23-06-2026

Mango has been added to the plants file with id: 606b6b14-d8aa-45d6-a852-298a3ce130b7.

In [7]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 2

Your plants:
                                     id    name
0  2a9902a4-43d6-4b46-8330-de1067281f8f  Cactus
1  1508c78d-3514-4525-aec3-471df5662440  cactus
2  606b6b14-d8aa-45d6-a852-298a3ce130b7   Mango

Enter the number of the plant you cared for:  4

Invalid choice! Please enter a number between 1 and 3.

In [3]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 2
Press Enter to continue or 'b' to go back:

Your plants:
                                     id    name
0  2a9902a4-43d6-4b46-8330-de1067281f8f  Cactus
1  1508c78d-3514-4525-aec3-471df5662440  cactus
2  606b6b14-d8aa-45d6-a852-298a3ce130b7   Mango

Enter the number of the plant you cared for:  2

Activities:
1. Watering
2. Fertilizing
3. Repotting
4. Pruning

Enter the activity number (1-4):  1

Watering recorded for cactus on 02-07-2026!

In [4]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 5

Number of plants found: 3

-----Plant Details-----
Name: Cactus
Location: Garden
Date Acquired: 01-02-2025
Watering Frequency: 7
Sunlight: High
Last Watered: 01-07-2026

-----Plant Details-----
Name: cactus
Location: Room
Date Acquired: 20-06-2026
Watering Frequency: 1
Sunlight: Low
Last Watered: 02-07-2026

-----Plant Details-----
Name: Mango
Location: Garden
Date Acquired: 01-01-2026
Watering Frequency: 4
Sunlight: Low
Last Watered: 23-06-2026