In [1]:
from P1 import *
from P2 import *
from P3 import *

In [3]:
load_plants()

,id,name,location,date_acquired,watering_frequency,sunlight,last_watered
0,2a9902a4-43d6-4b46-8330-de1067281f8f,Cactus,Garden,01-02-2025,7,High,20-06-2026

In [4]:
load_care_log()

Empty DataFrame
Columns: [plant_id, activity, dat]
Index: []

In [2]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 1
Press Enter to continue or 'b' to go back:
Enter Plant name/species:  Cactus
Location in home:  Garden
Date acquired "Day-Month-Year" :  01-02-2025
Watering frequency (in days) : 7
Sunlight needs (Low, Medium, High) : high
When was the plant last watered? "Day-Month-Year": 20-06-2026

Cactus has been added to the plants file with id: 2a9902a4-43d6-4b46-8330-de1067281f8f.

In [4]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 3

 Plants due for care:
-------------------------
 Cactus - last watered 11 days ago (every 7 days)
-------------------------

In [2]:
main_menu()

Welcome to the Plant Care Tracker
1. Add a new plant to the collection
2. Record a plant care activity
3. View plants due for care
4. Search plants by name or location
5. View all plants
6. Exit application
7. Add photo to a plant.

Please enter your choice to use the application (1-7) 3

 Plants due for care:
-------------------------
cactus (ID: 1508c78d-3514-4525-aec3-471df5662440) - last watered 4 days ago (every 1 days)
-------------------------